// prisma/seedDefaultCode.js
// node prisma/seedDefaultCode.js

import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

/*  Java = 1 ,  C++ = 2 ,  Python = 3  */
const LANG = { JAVA: 1, CPP: 2, PYTHON: 3 };

/* 25 problems × 3 languages = 75 rows */
const rows = [
  // 1. Two-Sum
  { problemId: 1,  languageId: LANG.JAVA,    code: 'class Solution {\n    public int[] twoSum(int[] nums, int target) {\n        // Write your code here\n    }\n}', fullCode: 'import java.util.*;\n\n//USER_CODE_HERE\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int numsSize = sc.nextInt();\n        int[] nums = new int[numsSize];\n        for (int i = 0; i < numsSize; i++) nums[i] = sc.nextInt();\n        int target = sc.nextInt();\n        Solution sol = new Solution();\n        int[] result = sol.twoSum(nums, target);\n        System.out.println(result[0] + " " + result[1]);\n    }\n}' },
  { problemId: 1,  languageId: LANG.CPP,     code: 'class Solution {\npublic:\n    vector<int> twoSum(vector<int>& nums, int target) {\n        // Write your code here\n    }\n};', fullCode: '#include <iostream>\n#include <vector>\n#include <unordered_map>\nusing namespace std;\n\n//USER_CODE_HERE\n\ntemplate<typename T>\nostream& operator<<(ostream& os, const vector<T>& v) {\n    for (size_t i = 0; i < v.size(); ++i) {\n        os << v[i] << (i == v.size() - 1 ? "" : " ");\n    }\n    return os;\n}\n\n/* ---------- driver ---------- */\nint main() {\n    ios::sync_with_stdio(false);\n    cin.tie(nullptr);\n\n    int numsSize;\n    if (!(cin >> numsSize)) return 0;\n    vector<int> nums(numsSize);\n    for (int &x : nums) cin >> x;\n\n    int target;\n    cin >> target;\n\n    Solution sol;\n    vector<int> res = sol.twoSum(nums, target);\n    cout << res << \'\\n\';\n    return 0;\n}' },
  { problemId: 1,  languageId: LANG.PYTHON,  code: 'class Solution:\n    def twoSum(self, nums: List[int], target: int) -> List[int]:\n        # Write your code here', fullCode: 'import sys\nfrom typing import List\n\nsys.setrecursionlimit(2000)\n\n#USER_CODE_HERE\n\nif __name__ == "__main__":\n    n = int(input())\n    nums = list(map(int, input().split()))\n    target = int(input())\n    sol = Solution()\n    result = sol.twoSum(nums, target)\n    print(" ".join(map(str, result)))' },

  // 2. Longest-Substring-Without-Repeating-Characters
  { problemId: 2,  languageId: LANG.JAVA,    code: 'class Solution {\n    public int lengthOfLongestSubstring(String s) {\n        // Write your code here\n    }\n}', fullCode: 'import java.util.*;\n\n//USER_CODE_HERE\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        Solution sol = new Solution();\n        int result = sol.lengthOfLongestSubstring(s);\n        System.out.println(result);\n    }\n}' },
  { problemId: 2,  languageId: LANG.CPP,     code: 'class Solution {\npublic:\n    int lengthOfLongestSubstring(string s) {\n        // Write your code here\n    }\n};', fullCode: '#include <bits/stdc++.h>\nusing namespace std;\n\n//USER_CODE_HERE\n\nint main() {\n    string s;\n    cin >> s;\n    Solution sol;\n    cout << sol.lengthOfLongestSubstring(s) << endl;\n    return 0;\n}' },
  { problemId: 2,  languageId: LANG.PYTHON,  code: 'class Solution:\n    def lengthOfLongestSubstring(self, s: str) -> int:\n        # Write your code here', fullCode: '#USER_CODE_HERE\nimport sys\nfrom typing import List\n\nsys.setrecursionlimit(2000)\n\nif __name__ == "__main__":\n    s = input().strip()\n    sol = Solution()\n    result = sol.lengthOfLongestSubstring(s)\n    print(result)' },

  // 3. Median-of-Two-Sorted-Arrays
  { problemId: 3,  languageId: LANG.JAVA,    code: 'class Solution {\n    public double findMedianSortedArrays(int[] nums1, int[] nums2) {\n        // Write your code here\n    }\n}', fullCode: 'import java.util.*;\n\n//USER_CODE_HERE\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int nums1Size = sc.nextInt();\n        int[] nums1 = new int[nums1Size];\n        for (int i = 0; i < nums1Size; i++) nums1[i] = sc.nextInt();\n        int nums2Size = sc.nextInt();\n        int[] nums2 = new int[nums2Size];\n        for (int i = 0; i < nums2Size; i++) nums2[i] = sc.nextInt();\n        Solution sol = new Solution();\n        double result = sol.findMedianSortedArrays(nums1, nums2);\n        System.out.println(result);\n    }\n}' },
  { problemId: 3,  languageId: LANG.CPP,     code: 'class Solution {\npublic:\n    double findMedianSortedArrays(vector<int>& nums1, vector<int>& nums2) {\n        // Write your code here\n    }\n};', fullCode: '#include <bits/stdc++.h>\nusing namespace std;\n\n//USER_CODE_HERE\n\nint main() {\n    int nums1Size; cin >> nums1Size;\n    vector<int> nums1(nums1Size);\n    for(int i=0; i<nums1Size; i++) cin >> nums1[i];\n    int nums2Size; cin >> nums2Size;\n    vector<int> nums2(nums2Size);\n    for(int i=0; i<nums2Size; i++) cin >> nums2[i];\n    Solution sol;\n    cout << sol.findMedianSortedArrays(nums1, nums2) << endl;\n    return 0;\n}' },
  { problemId: 3,  languageId: LANG.PYTHON,  code: 'class Solution:\n    def findMedianSortedArrays(self, nums1: List[int], nums2: List[int]) -> float:\n        # Write your code here\n        pass', fullCode: '#USER_CODE_HERE\nimport sys\nfrom typing import List\n\nsys.setrecursionlimit(2000)\n\nif __name__ == "__main__":\n    nums1 = list(map(int, input().split()))\n    nums2 = list(map(int, input().split()))\n    sol = Solution()\n    result = sol.findMedianSortedArrays(nums1, nums2)\n    print(result)' },

  // 4. Longest-Palindromic-Substring
  { problemId: 4,  languageId: LANG.JAVA,    code: 'class Solution {\n    public String longestPalindrome(String s) {\n        // Write your code here\n    }\n}', fullCode: 'import java.util.*;\n\n//USER_CODE_HERE\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        Solution sol = new Solution();\n        String result = sol.longestPalindrome(s);\n        System.out.println(result);\n    }\n}' },
  { problemId: 4,  languageId: LANG.CPP,     code: 'class Solution {\npublic:\n    string longestPalindrome(string s) {\n        // Write your code here\n    }\n};', fullCode: '#include <bits/stdc++.h>\nusing namespace std;\n\n//USER_CODE_HERE\n\nint main() {\n    string s; cin >> s;\n    Solution sol;\n    string result = sol.longestPalindrome(s);\n    cout << result << endl;\n    return 0;\n}' },
  { problemId: 4,  languageId: LANG.PYTHON,  code: 'class Solution:\n    def longestPalindrome(self, s: str) -> str:\n        # Write your code here', fullCode: '#USER_CODE_HERE\nimport sys\nfrom typing import List\n\nsys.setrecursionlimit(2000)\n\nif __name__ == "__main__":\n    s = input().strip()\n    sol = Solution()\n    result = sol.longestPalindrome(s)\n    print(result)' },

  // 5. Reverse-Integer
  { problemId: 5,  languageId: LANG.JAVA,    code: 'class Solution {\n    public int reverse(int x) {\n        // Write your code here\n    }\n}', fullCode: 'import java.util.*;\n\n//USER_CODE_HERE\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int x = sc.nextInt();\n        Solution sol = new Solution();\n        int result = sol.reverse(x);\n        System.out.println(result);\n    }\n}' },
  { problemId: 5,  languageId: LANG.CPP,     code: 'class Solution {\npublic:\n    int reverse(int x) {\n        // Write your code here\n    }\n};', fullCode: '#include <bits/stdc++.h>\nusing namespace std;\n\n//USER_CODE_HERE\n\nint main() {\n    int x; cin >> x;\n    Solution sol;\n    int result = sol.reverse(x);\n    cout << result << endl;\n    return 0;\n}' },
  { problemId: 5,  languageId: LANG.PYTHON,  code: 'class Solution:\n    def reverse(self, x: int) -> int:\n        # Write your code here', fullCode: '#USER_CODE_HERE\nimport sys\nfrom typing import List\n\nsys.setrecursionlimit(2000)\n\nif __name__ == "__main__":\n    x = int(input())\n    sol = Solution()\n    result = sol.reverse(x)\n    print(result)' },

  // 6. String-to-Integer-atoi
  { problemId: 6,  languageId: LANG.JAVA,    code: 'class Solution {\n    public int myAtoi(String s) {\n        // Write your code here\n    }\n}', fullCode: 'import java.util.*;\n\n//USER_CODE_HERE\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.nextLine();\n        Solution sol = new Solution();\n        int result = sol.myAtoi(s);\n        System.out.println(result);\n    }\n}' },
  { problemId: 6,  languageId: LANG.CPP,     code: 'class Solution {\npublic:\n    int myAtoi(string s) {\n        // Write your code here\n    }\n};', fullCode: '#include <bits/stdc++.h>\nusing namespace std;\n\n//USER_CODE_HERE\n\nint main() {\n    string s;\n    getline(cin, s);\n    Solution sol;\n    int result = sol.myAtoi(s);\n    cout << result << endl;\n    return 0;\n}' },
  { problemId: 6,  languageId: LANG.PYTHON,  code: 'class Solution:\n    def myAtoi(self, s: str) -> int:\n        # Write your code here', fullCode: '#USER_CODE_HERE\nimport sys\nfrom typing import List\n\nsys.setrecursionlimit(2000)\n\nif __name__ == "__main__":\n    s = input().strip()\n    sol = Solution()\n    result = sol.myAtoi(s)\n    print(result)' },

  // 7. Palindrome-Number
  { problemId: 7,  languageId: LANG.JAVA,    code: 'class Solution {\n    public boolean isPalindrome(int x) {\n        // Write your code here\n    }\n}', fullCode: 'import java.util.*;\n\n//USER_CODE_HERE\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int x = sc.nextInt();\n        Solution sol = new Solution();\n        boolean result = sol.isPalindrome(x);\n        System.out.println(result);\n    }\n}' },
  { problemId: 7,  languageId: LANG.CPP,     code: 'class Solution {\npublic:\n    bool isPalindrome(int x) {\n        // Write your code here\n    }\n};', fullCode: '#include <bits/stdc++.h>\nusing namespace std;\n\n//USER_CODE_HERE\n\nint main() {\n    int x; cin >> x;\n    Solution sol;\n    bool result = sol.isPalindrome(x);\n    cout << (result ? "true" : "false") << endl;\n    return 0;\n}' },
  { problemId: 7,  languageId: LANG.PYTHON,  code: 'class Solution:\n    def isPalindrome(self, x: int) -> bool:\n        # Write your code here', fullCode: '#USER_CODE_HERE\nimport sys\nsys.setrecursionlimit(2000)\n\nif __name__ == "__main__":\n    x = int(input())\n    sol = Solution()\n    print("true" if sol.isPalindrome(x) else "false")' },

  // 8. Container-With-Most-Water
  { problemId: 8,  languageId: LANG.JAVA,    code: 'class Solution {\n    public int maxArea(int[] height) {\n        // Write your code here\n    }\n}', fullCode: 'import java.util.*;\n\n//USER_CODE_HERE\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int heightSize = sc.nextInt();\n        int[] height = new int[heightSize];\n        for (int i = 0; i < heightSize; i++) height[i] = sc.nextInt();\n        Solution sol = new Solution();\n        int result = sol.maxArea(height);\n        System.out.println(result);\n    }\n}' },
  { problemId: 8,  languageId: LANG.CPP,     code: 'class Solution {\npublic:\n    int maxArea(vector<int>& height) {\n        // Write your code here\n    }\n};', fullCode: '#include <bits/stdc++.h>\nusing namespace std;\n\n//USER_CODE_HERE\n\nint main() {\n    int heightSize; cin >> heightSize;\n    vector<int> height(heightSize);\n    for(int i=0; i<heightSize; i++) cin >> height[i];\n    Solution sol;\n    int result = sol.maxArea(height);\n    cout << result << endl;\n    return 0;\n}' },
  { problemId: 8,  languageId: LANG.PYTHON,  code: 'class Solution:\n    def maxArea(self, height: List[int]) -> int:\n        # Write your code here', fullCode: 'from typing import List\n\n#USER_CODE_HERE\n\nimport sys\nsys.setrecursionlimit(2000)\nif __name__ == "__main__":\n    n = int(input())\n    height = list(map(int, input().split()))\n    sol = Solution()\n    result = sol.maxArea(height)\n    print(result)' },

  // 9. Integer-to-Roman
  { problemId: 9,  languageId: LANG.JAVA,    code: 'class Solution {\n    public String intToRoman(int num) {\n        // Write your code here\n    }\n}', fullCode: 'import java.util.*;\n\n//USER_CODE_HERE\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int num = sc.nextInt();\n        Solution sol = new Solution();\n        String result = sol.intToRoman(num);\n        System.out.println(result);\n    }\n}' },
  { problemId: 9,  languageId: LANG.CPP,     code: 'class Solution {\npublic:\n    string intToRoman(int num) {\n        // Write your code here\n    }\n};', fullCode: '#include <bits/stdc++.h>\nusing namespace std;\n\n//USER_CODE_HERE\n\nint main() {\n    int num; cin >> num;\n    Solution sol;\n    string result = sol.intToRoman(num);\n    cout << result << endl;\n    return 0;\n}' },
  { problemId: 9,  languageId: LANG.PYTHON,  code: 'class Solution:\n    def intToRoman(self, num: int) -> str:\n        # Write your code here', fullCode: '#USER_CODE_HERE\nimport sys\nfrom typing import List\n\nsys.setrecursionlimit(2000)\n\nif __name__ == "__main__":\n    num = int(input())\n    sol = Solution()\n    result = sol.intToRoman(num)\n    print(result)' },

  // 10. Roman-to-Integer
  { problemId: 10, languageId: LANG.JAVA,    code: 'class Solution {\n    public int romanToInt(String s) {\n        // Write your code here\n    }\n}', fullCode: 'import java.util.*;\n\n//USER_CODE_HERE\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        Solution sol = new Solution();\n        int result = sol.romanToInt(s);\n        System.out.println(result);\n    }\n}' },
  { problemId: 10, languageId: LANG.CPP,     code: 'class Solution {\npublic:\n    int romanToInt(string s) {\n        // Write your code here\n    }\n};', fullCode: '#include <bits/stdc++.h>\nusing namespace std;\n\n//USER_CODE_HERE\n\nint main() {\n    string s; cin >> s;\n    Solution sol;\n    int result = sol.romanToInt(s);\n    cout << result << endl;\n    return 0;\n}' },
  { problemId: 10, languageId: LANG.PYTHON,  code: 'class Solution:\n    def romanToInt(self, s: str) -> int:\n        # Write your code here', fullCode: '#USER_CODE_HERE\nimport sys\nfrom typing import List\n\nsys.setrecursionlimit(2000)\n\nif __name__ == "__main__":\n    s = input().strip()\n    sol = Solution()\n    result = sol.romanToInt(s)\n    print(result)' },

  // 11. Longest-Common-Prefix
  { problemId: 11, languageId: LANG.JAVA,    code: 'class Solution {\n    public String longestCommonPrefix(String[] strs) {\n        // Write your code here\n    }\n}', fullCode: 'import java.util.*;\n\n//USER_CODE_HERE\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int strsSize = sc.nextInt();\n        String[] strs = new String[strsSize];\n        for (int i = 0; i < strsSize; i++) strs[i] = sc.next();\n        Solution sol = new Solution();\n        String result = sol.longestCommonPrefix(strs);\n        System.out.println(result);\n    }\n}' },
  { problemId: 11, languageId: LANG.CPP,     code: 'class Solution {\npublic:\n    string longestCommonPrefix(vector<string>& strs) {\n        // Write your code here\n    }\n};', fullCode: '#include <bits/stdc++.h>\nusing namespace std;\n\n//USER_CODE_HERE\n\nint main() {\n    int strsSize; cin >> strsSize;\n    vector<string> strs(strsSize);\n    for(int i=0; i<strsSize; i++) cin >> strs[i];\n    Solution sol;\n    string result = sol.longestCommonPrefix(strs);\n    cout << result << endl;\n    return 0;\n}' },
  { problemId: 11, languageId: LANG.PYTHON,  code: 'class Solution:\n    def longestCommonPrefix(self, strs: List[str]) -> str:\n        # Write your code here', fullCode: 'from typing import List\n\n#USER_CODE_HERE\n\nif __name__ == "__main__":\n    n = int(input())\n    strs = [input().strip() for _ in range(n)]\n    print(Solution().longestCommonPrefix(strs))' },

  // 12. 3Sum
  { problemId: 12, languageId: LANG.JAVA,    code: 'class Solution {\n    public List<List<Integer>> threeSum(int[] nums) {\n        // Write your code here\n    }\n}', fullCode: 'import java.util.*;\n\n//USER_CODE_HERE\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int numsSize = sc.nextInt();\n        int[] nums = new int[numsSize];\n        for (int i = 0; i < numsSize; i++) nums[i] = sc.nextInt();\n        Solution sol = new Solution();\n        List<List<Integer>> result = sol.threeSum(nums);\n        System.out.println(result);\n    }\n}' },
  { problemId: 12, languageId: LANG.CPP,     code: 'class Solution {\npublic:\n    vector<vector<int>> threeSum(vector<int>& nums) {\n        // Write your code here\n    }\n};', fullCode: '#include <bits/stdc++.h>\nusing namespace std;\n\n//USER_CODE_HERE\nint main() {\n    int numsSize; cin >> numsSize;\n    vector<int> nums(numsSize);\n    for(int i=0; i<numsSize; i++) cin >> nums[i];\n    Solution sol;\n    vector<vector<int>> result = sol.threeSum(nums);\n    cout << "[";\n    for(int i = 0; i < result.size(); i++) {\n        cout << "[";\n        for(int j = 0; j < result[i].size(); j++) {\n            cout << result[i][j];\n            if(j < result[i].size()-1) cout << ", ";\n        }\n        cout << "]";\n        if(i < result.size()-1) cout << ", ";\n    }\n    cout << "]" << endl;\n    return 0;\n}' },
  { problemId: 12, languageId: LANG.PYTHON,  code: 'class Solution:\n    def threeSum(self, nums: List[int]) -> List[List[int]]:\n        # Write your code here\n        pass', fullCode: 'from typing import List\n\n#USER_CODE_HERE\n\nif __name__ == "__main__":\n    import sys\n    n = int(input())\n    nums = list(map(int, input().split()))\n    assert len(nums) == n\n    print(Solution().threeSum(nums))' },

  // 13. 3Sum-Closest
  { problemId: 13, languageId: LANG.JAVA,    code: 'class Solution {\n    public int threeSumClosest(int[] nums, int target) {\n        // Write your code here\n    }\n}', fullCode: 'import java.util.*;\n\n//USER_CODE_HERE\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int numsSize = sc.nextInt();\n        int[] nums = new int[numsSize];\n        for (int i = 0; i < numsSize; i++) nums[i] = sc.nextInt();\n        int target = sc.nextInt();\n        Solution sol = new Solution();\n        int result = sol.threeSumClosest(nums, target);\n        System.out.println(result);\n    }\n}' },
  { problemId: 13, languageId: LANG.CPP,     code: 'class Solution {\npublic:\n    int threeSumClosest(vector<int>& nums, int target) {\n        // Write your code here\n    }\n};', fullCode: '#include <bits/stdc++.h>\nusing namespace std;\n\n//USER_CODE_HERE\n\nint main() {\n    int numsSize; cin >> numsSize;\n    vector<int> nums(numsSize);\n    for(int i=0; i<numsSize; i++) cin >> nums[i];\n    int target; cin >> target;\n    Solution sol;\n    cout << sol.threeSumClosest(nums, target) << endl;\n    return 0;\n}' },
  { problemId: 13, languageId: LANG.PYTHON,  code: 'class Solution:\n    def threeSumClosest(self, nums: List[int], target: int) -> int:\n        # Write your code here\n        pass', fullCode: '#USER_CODE_HERE\nimport sys\nfrom typing import List\n\nsys.setrecursionlimit(2000)\n\nif __name__ == "__main__":\n    nums = list(map(int, input().split()))\n    target = int(input())\n    sol = Solution()\n    result = sol.threeSumClosest(nums, target)\n    print(result)' },

  // 14. Letter-Combinations-of-a-Phone-Number
  { problemId: 14, languageId: LANG.JAVA,    code: 'class Solution {\n    public List<String> letterCombinations(String digits) {\n        // Write your code here\n    }\n}', fullCode: '//USER_CODE_HERE\nimport java.util.*;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String digits = sc.next();\n        Solution sol = new Solution();\n        List<String> result = sol.letterCombinations(digits);\n        System.out.println(result);\n    }\n}' },
  { problemId: 14, languageId: LANG.CPP,     code: 'class Solution {\npublic:\n    vector<string> letterCombinations(string digits) {\n        // Write your code here\n    }\n};', fullCode: '//USER_CODE_HERE\n#include <iostream>\n#include <vector>\n#include <string>\nusing namespace std;\n\ntemplate<typename T>\nostream& operator<<(ostream& os, const vector<T>& v) {\n    os << "[";\n    for (size_t i = 0; i < v.size(); ++i) {\n        os << v[i] << (i == v.size() - 1 ? "" : ",");\n    }\n    os << "]";\n    return os;\n}\n\nint main() {\n    string digits; cin >> digits;\n    Solution sol;\n    vector<string> result = sol.letterCombinations(digits);\n    cout << result << endl;\n    return 0;\n}' },
  { problemId: 14, languageId: LANG.PYTHON,  code: 'class Solution:\n    def letterCombinations(self, digits: str) -> List[str]:\n        # Write your code here\n        pass', fullCode: '#USER_CODE_HERE\nimport sys\nfrom typing import List\n\nsys.setrecursionlimit(2000)\n\nif __name__ == "__main__":\n    digits = input().strip()\n    sol = Solution()\n    result = sol.letterCombinations(digits)\n    print(result)' },

  // 15. 4Sum
  { problemId: 15, languageId: LANG.JAVA,    code: 'class Solution {\n    public List<List<Integer>> fourSum(int[] nums, int target) {\n        // Write your code here\n    }\n}', fullCode: 'import java.util.*;\n\n//USER_CODE_HERE\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int numsSize = sc.nextInt();\n        int[] nums = new int[numsSize];\n        for (int i = 0; i < numsSize; i++) nums[i] = sc.nextInt();\n        int target = sc.nextInt();\n        Solution sol = new Solution();\n        List<List<Integer>> result = sol.fourSum(nums, target);\n        System.out.println(result);\n    }\n}' },
  { problemId: 15, languageId: LANG.CPP,     code: 'class Solution {\npublic:\n    vector<vector<int>> fourSum(vector<int>& nums, int target) {\n        // Write your code here\n    }\n};', fullCode: '#include <bits/stdc++.h>\nusing namespace std;\n\n//USER_CODE_HERE\n\nvoid printResult(const vector<vector<int>>& result) {\n    cout << "[";\n    for (int i = 0; i < result.size(); i++) {\n        cout << "[";\n        for (int j = 0; j < result[i].size(); j++) {\n            cout << result[i][j];\n            if (j < result[i].size() - 1) cout << ", ";\n        }\n        cout << "]";\n        if (i < result.size() - 1) cout << ", ";\n    }\n    cout << "]" << endl;\n}\n\nint main() {\n    int numsSize; cin >> numsSize;\n    vector<int> nums(numsSize);\n    for(int i = 0; i < numsSize; i++) cin >> nums[i];\n    int target; cin >> target;\n    Solution sol;\n    vector<vector<int>> result = sol.fourSum(nums, target);\n    printResult(result);\n    return 0;\n}' },
  { problemId: 15, languageId: LANG.PYTHON,  code: 'class Solution:\n    def fourSum(self, nums: List[int], target: int) -> List[List[int]]:\n        # Write your code here\n        pass', fullCode: 'from typing import List\n\n#USER_CODE_HERE\n\nif __name__ == "__main__":\n    n = int(input())\n    nums = list(map(int, input().split()))\n    target = int(input())\n    sol = Solution()\n    result = sol.fourSum(nums, target)\n    print(result)' },

  // 16. Valid-Parentheses
  { problemId: 16, languageId: LANG.JAVA,    code: 'class Solution {\n    public boolean isValid(String s) {\n        // Write your code here\n    }\n}', fullCode: 'import java.util.*;\n\n//USER_CODE_HERE\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        Solution sol = new Solution();\n        boolean result = sol.isValid(s);\n        System.out.println(result);\n    }\n}' },
  { problemId: 16, languageId: LANG.CPP,     code: 'class Solution {\npublic:\n    bool isValid(string s) {\n        // Write your code here\n    }\n};', fullCode: '#include <bits/stdc++.h>\nusing namespace std;\n\n//USER_CODE_HERE\n\nint main() {\n    string s; cin >> s;\n    Solution sol;\n    bool result = sol.isValid(s);\n    cout << (result ? "true" : "false") << endl;\n    return 0;\n}' },
  { problemId: 16, languageId: LANG.PYTHON,  code: 'class Solution:\n    def isValid(self, s: str) -> bool:\n        # Write your code here\n        pass', fullCode: '#USER_CODE_HERE\nimport sys\nfrom typing import List\n\nsys.setrecursionlimit(2000)\n\nif __name__ == "__main__":\n    s = input().strip()\n    sol = Solution()\n    result = sol.isValid(s)\n    print(str(result).lower())' },

  // 17. Generate-Parentheses
  { problemId: 17, languageId: LANG.JAVA,    code: 'class Solution {\n    public List<String> generateParenthesis(int n) {\n        // Write your code here\n    }\n}', fullCode: 'import java.util.*;\n\n//USER_CODE_HERE\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        Solution sol = new Solution();\n        List<String> result = sol.generateParenthesis(n);\n        System.out.println(result);\n    }\n}' },
  { problemId: 17, languageId: LANG.CPP,     code: 'class Solution {\npublic:\n    vector<string> generateParenthesis(int n) {\n        // Write your code here\n    }\n};', fullCode: '#include <bits/stdc++.h>\nusing namespace std;\n\n//USER_CODE_HERE\n\ntemplate<typename T>\nostream& operator<<(ostream& os, const vector<T>& v) {\n    os << "[";\n    for (size_t i = 0; i < v.size(); ++i) {\n        os << v[i] << (i == v.size() - 1 ? "" : ",");\n    }\n    os << "]";\n    return os;\n}\n\nint main() {\n    int n; cin >> n;\n    Solution sol;\n    vector<string> result = sol.generateParenthesis(n);\n    cout << result << endl;\n    return 0;\n}' },
  { problemId: 17, languageId: LANG.PYTHON,  code: 'class Solution:\n    def generateParenthesis(self, n: int) -> List[str]:\n        # Write your code here\n        pass', fullCode: '#USER_CODE_HERE\nimport sys\nfrom typing import List\n\nsys.setrecursionlimit(2000)\n\nif __name__ == "__main__":\n    n = int(input())\n    sol = Solution()\n    result = sol.generateParenthesis(n)\n    print(result)' },

  // 18. Remove-Duplicates-from-Sorted-Array
  { problemId: 18, languageId: LANG.JAVA,    code: 'class Solution {\n    public int removeDuplicates(int[] nums) {\n        // Write your code here\n    }\n}', fullCode: 'import java.util.*;\n\n//USER_CODE_HERE\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int numsSize = sc.nextInt();\n        int[] nums = new int[numsSize];\n        for (int i = 0; i < numsSize; i++) nums[i] = sc.nextInt();\n        Solution sol = new Solution();\n        int result = sol.removeDuplicates(nums);\n        System.out.println(result);\n    }\n}' },
  { problemId: 18, languageId: LANG.CPP,     code: 'class Solution {\npublic:\n    int removeDuplicates(vector<int>& nums) {\n        // Write your code here\n    }\n};', fullCode: '#include <bits/stdc++.h>\nusing namespace std;\n\n//USER_CODE_HERE\n\nint main() {\n    int numsSize; cin >> numsSize;\n    vector<int> nums(numsSize);\n    for(int i=0; i<numsSize; i++) cin >> nums[i];\n    Solution sol;\n    int result = sol.removeDuplicates(nums);\n    cout << result << endl;\n    return 0;\n}' },
  { problemId: 18, languageId: LANG.PYTHON,  code: 'class Solution:\n    def removeDuplicates(self, nums: List[int]) -> int:\n        # Write your code here\n        pass', fullCode: 'import sys\nfrom typing import List\n\n#USER_CODE_HERE\n\nif __name__ == "__main__":\n    n = int(input())\n    nums = list(map(int, input().split()))\n    sol = Solution()\n    result = sol.removeDuplicates(nums)\n    print(result)' },

  // 19. Remove-Element
  { problemId: 19, languageId: LANG.JAVA,    code: 'class Solution {\n    public int removeElement(int[] nums, int val) {\n        // Write your code here\n    }\n}', fullCode: 'import java.util.*;\n\n//USER_CODE_HERE\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int numsSize = sc.nextInt();\n        int[] nums = new int[numsSize];\n        for (int i = 0; i < numsSize; i++) nums[i] = sc.nextInt();\n        int val = sc.nextInt();\n        Solution sol = new Solution();\n        int result = sol.removeElement(nums, val);\n        System.out.println(result);\n    }\n}' },
  { problemId: 19, languageId: LANG.CPP,     code: 'class Solution {\npublic:\n    int removeElement(vector<int>& nums, int val) {\n        // Write your code here\n    }\n};', fullCode: '#include <bits/stdc++.h>\nusing namespace std;\n\n//USER_CODE_HERE\n\nint main() {\n    int numsSize; cin >> numsSize;\n    vector<int> nums(numsSize);\n    for(int i=0; i<numsSize; i++) cin >> nums[i];\n    int val; cin >> val;\n    Solution sol;\n    int result = sol.removeElement(nums, val);\n    cout << result << endl;\n    return 0;\n}' },
  { problemId: 19, languageId: LANG.PYTHON,  code: 'class Solution:\n    def removeElement(self, nums: List[int], val: int) -> int:\n        # Write your code here\n        pass', fullCode: 'from typing import List\n\n#USER_CODE_HERE\n\nif __name__ == "__main__":\n    n = int(input().strip())\n    nums = list(map(int, input().split()))\n    val = int(input().strip())\n    sol = Solution()\n    result = sol.removeElement(nums, val)\n    print(result)' },

  // 20. Implement-strStr()
  { problemId: 20, languageId: LANG.JAVA,    code: 'class Solution {\n    public int strStr(String haystack, String needle) {\n        // Write your code here\n    }\n}', fullCode: 'import java.util.*;\n\n//USER_CODE_HERE\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String haystack = sc.next();\n        String needle = sc.next();\n        Solution sol = new Solution();\n        int result = sol.strStr(haystack, needle);\n        System.out.println(result);\n    }\n}' },
  { problemId: 20, languageId: LANG.CPP,     code: 'class Solution {\npublic:\n    int strStr(string haystack, string needle) {\n        // Write your code here\n    }\n};', fullCode: '#include <bits/stdc++.h>\nusing namespace std;\n\n//USER_CODE_HERE\n\nint main() {\n    string haystack, needle;\n    cin >> haystack >> needle;\n    Solution sol;\n    int result = sol.strStr(haystack, needle);\n    cout << result << endl;\n    return 0;\n}' },
  { problemId: 20, languageId: LANG.PYTHON,  code: 'class Solution:\n    def strStr(self, haystack: str, needle: str) -> int:\n        # Write your code here\n        pass', fullCode: 'import sys\nfrom typing import List\n\n#USER_CODE_HERE\n\nif __name__ == "__main__":\n    haystack = input().strip()\n    needle = input().strip()\n    sol = Solution()\n    result = sol.strStr(haystack, needle)\n    print(result)' },

  // 21. Divide-Two-Integers
  { problemId: 21, languageId: LANG.JAVA,    code: 'class Solution {\n    public int divide(int dividend, int divisor) {\n        // Write your code here\n    }\n}', fullCode: 'import java.util.*;\n\n//USER_CODE_HERE\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int dividend = sc.nextInt();\n        int divisor = sc.nextInt();\n        Solution sol = new Solution();\n        int result = sol.divide(dividend, divisor);\n        System.out.println(result);\n    }\n}' },
  { problemId: 21, languageId: LANG.CPP,     code: 'class Solution {\npublic:\n    int divide(int dividend, int divisor) {\n        // Write your code here\n    }\n};', fullCode: '#include <bits/stdc++.h>\nusing namespace std;\n\n//USER_CODE_HERE\n\nint main() {\n    int dividend, divisor; cin >> dividend >> divisor;\n    Solution sol;\n    int result = sol.divide(dividend, divisor);\n    cout << result << endl;\n    return 0;\n}' },
  { problemId: 21, languageId: LANG.PYTHON,  code: 'class Solution:\n    def divide(self, dividend: int, divisor: int) -> int:\n        # Write your code here\n        pass', fullCode: '#USER_CODE_HERE\nimport sys\nfrom typing import List\n\nif __name__ == "__main__":\n    input_line = input().strip()\n    if \' \' in input_line:\n        dividend, divisor = map(int, input_line.split())\n    else:\n        dividend = int(input_line)\n        divisor = int(input())\n    sol = Solution()\n    result = sol.divide(dividend, divisor)\n    print(result)' },

  // 22. Next-Permutation
  { problemId: 22, languageId: LANG.JAVA,    code: 'class Solution {\n    public int[] nextPermutation(int[] nums) {\n        // Write your code here\n    }\n}', fullCode: 'import java.util.*;\n\n//USER_CODE_HERE\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int numsSize = sc.nextInt();\n        int[] nums = new int[numsSize];\n        for (int i = 0; i < numsSize; i++) nums[i] = sc.nextInt();\n        Solution sol = new Solution();\n        sol.nextPermutation(nums);\n        System.out.println(Arrays.toString(nums));\n    }\n}' },
  { problemId: 22, languageId: LANG.CPP,     code: 'class Solution {\npublic:\n    vector<int> nextPermutation(vector<int>& nums) {\n        // Write your code here\n    }\n};', fullCode: '#include <bits/stdc++.h>\nusing namespace std;\n\n//USER_CODE_HERE\ntemplate<typename T>\nostream& operator<<(ostream& os, const vector<T>& v) {\n    os << "[";\n    for (size_t i = 0; i < v.size(); ++i) {\n        os << v[i]; if (i != v.size() - 1) os << ", ";\n    }\n    os << "]"; return os;\n}\n\nint main() {\n    int numsSize; cin >> numsSize;\n    vector<int> nums(numsSize);\n    for(int i = 0; i < numsSize; i++) cin >> nums[i];\n    Solution sol;\n    sol.nextPermutation(nums);\n    cout << nums << endl;\n    return 0;\n}' },
  { problemId: 22, languageId: LANG.PYTHON,  code: 'class Solution:\n    def nextPermutation(self, nums: List[int]) -> List[int]:\n        # Write your code here\n        pass', fullCode: 'import sys\nfrom typing import List\n\n#USER_CODE_HERE\n\nif __name__ == "__main__":\n    n = int(input().strip())\n    nums = list(map(int, input().split()))\n    sol = Solution()\n    sol.nextPermutation(nums)\n    print(nums)' },

  // 23. Longest-Valid-Parentheses
  { problemId: 23, languageId: LANG.JAVA,    code: 'class Solution {\n    public int longestValidParentheses(String s) {\n        // Write your code here\n    }\n}', fullCode: 'import java.util.*;\n\n//USER_CODE_HERE\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String s = sc.next();\n        Solution sol = new Solution();\n        int result = sol.longestValidParentheses(s);\n        System.out.println(result);\n    }\n}' },
  { problemId: 23, languageId: LANG.CPP,     code: 'class Solution {\npublic:\n    int longestValidParentheses(string& s) {\n        // Write your code here\n    }\n};', fullCode: '#include <bits/stdc++.h>\nusing namespace std;\n\n//USER_CODE_HERE\n\nint main() {\n    string s; cin >> s;\n    Solution sol;\n    int result = sol.longestValidParentheses(s);\n    cout << result << endl;\n    return 0;\n}' },
  { problemId: 23, languageId: LANG.PYTHON,  code: 'class Solution:\n    def longestValidParentheses(self, s: str) -> int:\n        # Write your code here\n        pass', fullCode: '#USER_CODE_HERE\nimport sys\nfrom typing import List\n\nsys.setrecursionlimit(2000)\n\nif __name__ == "__main__":\n    s = input().strip()\n    sol = Solution()\n    result = sol.longestValidParentheses(s)\n    print(result)' },

  // 24. Search-in-Rotated-Sorted-Array
  { problemId: 24, languageId: LANG.JAVA,    code: 'class Solution {\n    public int search(int[] nums, int target) {\n        // Write your code here\n    }\n}', fullCode: 'import java.util.*;\n\n//USER_CODE_HERE\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int numsSize = sc.nextInt();\n        int[] nums = new int[numsSize];\n        for (int i = 0; i < numsSize; i++) nums[i] = sc.nextInt();\n        int target = sc.nextInt();\n        Solution sol = new Solution();\n        int result = sol.search(nums, target);\n        System.out.println(result);\n    }\n}' },
  { problemId: 24, languageId: LANG.CPP,     code: 'class Solution {\npublic:\n    int search(vector<int>& nums, int target) {\n        // Write your code here\n    }\n};', fullCode: '#include <bits/stdc++.h>\nusing namespace std;\n\n//USER_CODE_HERE\n\nint main() {\n    int numsSize; cin >> numsSize;\n    vector<int> nums(numsSize);\n    for(int i=0; i<numsSize; i++) cin >> nums[i];\n    int target; cin >> target;\n    Solution sol;\n    int result = sol.search(nums, target);\n    cout << result << endl;\n    return 0;\n}' },
  { problemId: 24, languageId: LANG.PYTHON,  code: 'class Solution:\n    def search(self, nums: List[int], target: int) -> int:\n        # Write your code here\n        pass', fullCode: '#USER_CODE_HERE\nimport sys\nfrom typing import List\n\nsys.setrecursionlimit(2000)\n\nif __name__ == "__main__":\n    nums = list(map(int, input().split()))\n    target = int(input())\n    sol = Solution()\n    result = sol.search(nums, target)\n    print(result)' },

  // 25. Find-First-and-Last-Position-of-Element-in-Sorted-Array
  { problemId: 25, languageId: LANG.JAVA,    code: 'class Solution {\n    public int[] searchRange(int[] nums, int target) {\n        // Write your code here\n    }\n}', fullCode: 'import java.util.*;\n\n//USER_CODE_HERE\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        String[] input = sc.nextLine().split(" ");\n        int target = Integer.parseInt(sc.nextLine());\n        int numsSize = input.length;\n        int[] nums = new int[numsSize];\n        for (int i = 0; i < numsSize; i++) nums[i] = Integer.parseInt(input[i]);\n        Solution sol = new Solution();\n        int[] result = sol.searchRange(nums, target);\n        System.out.println(Arrays.toString(result));\n    }\n}' },
  { problemId: 25, languageId: LANG.CPP,     code: 'class Solution {\npublic:\n    vector<int> searchRange(vector<int>& nums, int target) {\n        // Write your code here\n    }\n};', fullCode: '#include <bits/stdc++.h>\nusing namespace std;\n\n//USER_CODE_HERE\ntemplate<typename T>\nostream& operator<<(ostream& os, const vector<T>& v) {\n    os << "[";\n    for (size_t i = 0; i < v.size(); ++i) {\n        os << v[i]; if (i != v.size() - 1) os << ", ";\n    }\n    os << "]"; return os;\n}\n\nint main() {\n    int numsSize; cin >> numsSize;\n    vector<int> nums(numsSize);\n    for(int i=0; i<numsSize; i++) cin >> nums[i];\n    int target; cin >> target;\n    Solution sol;\n    vector<int> result = sol.searchRange(nums, target);\n    cout << result << endl;\n    return 0;\n}' },
  { problemId: 25, languageId: LANG.PYTHON,  code: 'class Solution:\n    def searchRange(self, nums: List[int], target: int) -> List[int]:\n        # Write your code here\n        pass', fullCode: '#USER_CODE_HERE\nimport sys\nfrom typing import List\n\nsys.setrecursionlimit(2000)\n\nif __name__ == "__main__":\n    nums = list(map(int, input().split()))\n    target = int(input())\n    sol = Solution()\n    result = sol.searchRange(nums, target)\n    print(result)' }
];

async function main() {
  for (const r of rows) {
    await prisma.defaultCode.upsert({
      where: {
        problemId_languageId: { problemId: r.problemId, languageId: r.languageId }
      },
      update: {}, // leave existing rows untouched
      create: r
    });
  }
  console.log(`✅  Seeded ${rows.length} default-code rows`);
}

main()
  .catch(e => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });